name: payment_reliability
version: '1.0.0'
config-version: 2
profile: payment_reliability
model-paths: [models]
test-paths: [tests]
clean-targets: [target, dbt_packages]
models:
  payment_reliability:
    +materialized: view
